import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { PrismaClient } from '@prisma/client';
import { createApp } from '../src/app.js';
import { parseEnv } from '../src/config/env.js';
import { SPECIAL_CAPTURE_BALL_REWARD_IDS } from '../src/services/captureBalls.js';
import { GYMS, ELITE, JOHTO_GYMS, HOENN_GYMS, SINNOH_GYMS, UNOVA1_GYMS, KALOS_GYMS, ALOLA_TRIALS, GALAR_GYMS, PALDEA_GYMS, PALDEA_ELITE } from '../src/services/battleRules.js';

test('MySQL: treinador paga dinheiro e itens; escolha selvagem exige campeão de Kanto', { skip: process.env.TEST_MYSQL !== '1' }, async () => {
  const db = new PrismaClient();
  const app = createApp({ db, config: parseEnv(process.env) });
  const login = `tr_${randomUUID().replaceAll('-', '').slice(0, 20)}`;
  let userId;
  try {
    const account = (await request(app).post('/api/auth/register').send({ login, senha: 'Trainer-test-145!', nomeTreinador: 'Treinador QA' }).expect(201)).body.data;
    userId = account.usuario.id;
    const auth = { Authorization: `Bearer ${account.token}` };
    const original = (await request(app).get('/api/jogador/save').set(auth).expect(200)).body.data;
    const save = (await request(app).post('/api/jogador/save').set(auth).send({ nomeTreinador: 'Treinador QA', substituirSaveId: original.id }).expect(201)).body.data;
    await request(app).post('/api/jogador/inicial').set(auth).send({ saveId: save.id, especieId: 4 }).expect(201);
    const starterItems = (await request(app).get('/api/jogador/inventario').set(auth).expect(200)).body.data;
    assert.equal(starterItems.find((entry) => entry.itemId === 'poke-ball').quantidade, 10);
    assert.equal(starterItems.find((entry) => entry.itemId === 'potion').quantidade, 5);
    const member = (await request(app).get('/api/jogador/pokemon').set(auth).expect(200)).body.data[0];
    const custom = { tipo: 'selvagem', selvagem: { regiao: 'kanto', especieId: 25, nivel: 77 } };
    await request(app).post('/api/batalhas/iniciar').set(auth).send(custom).expect(403);
    const status = (await request(app).get('/api/batalhas/desafios').set(auth).expect(200)).body.data;
    assert.equal(status.regioes[0].escolhaSelvagem, false);
    const battle = (await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'treinador', dificuldade: 'facil' }).expect(201)).body.data;
    assert.equal(battle.tipo, 'treinador');
    assert.ok(battle.totalOponentes >= 2 && battle.totalOponentes <= 3);
    assert.ok([battle.oponente, ...battle.fila].every((entry) => entry.nivel >= 20 && entry.nivel <= 30));
    const chosen = (await request(app).post('/api/batalhas/acao').set(auth).send({ batalhaId: battle.id, versao: 0, acao: 'escolher', pokemonId: member.id }).expect(200)).body.data;
    const setup = structuredClone(chosen);
    setup.fila = [];
    setup.oponente.hp = 1;
    setup.oponente.tipos = ['normal'];
    setup.jogador.stats.speed = 999;
    setup.jogador.ataques[0].prioridade = 10;
    setup.jogador.ataques[0].poder = 10000;
    setup.jogador.ataques[0].precisao = 100;
    await db.batalha.update({ where: { id: battle.id }, data: { estado: setup } });
    const result = (await request(app).post('/api/batalhas/acao').set(auth).send({ batalhaId: battle.id, versao: 1, acao: 'ataque', golpe: setup.jogador.ataques[0].nome }).expect(200)).body.data;
    assert.equal(result.resultado, 'vitoria');
    assert.ok((await request(app).get('/api/jogador/historico').set(auth).expect(200)).body.data.eventos.some((entry) => entry.tipo === 'vencer_treinador' && entry.dificuldade === 'facil'));
    assert.equal(result.moedasGanhas, 1000);
    const ballReward = result.itensGanhos.find((entry) => SPECIAL_CAPTURE_BALL_REWARD_IDS.includes(entry.itemId));
    assert.deepEqual(ballReward, { itemId: ballReward.itemId, quantidade: 2 });
    assert.ok(!result.itensGanhos.some((entry) => entry.itemId === 'poke-ball'));
    assert.equal((await request(app).get('/api/jogador/save').set(auth).expect(200)).body.data.moedas, 1000);
    const inventory = (await request(app).get('/api/jogador/inventario').set(auth).expect(200)).body.data;
    assert.equal(inventory.find((entry) => entry.itemId === 'poke-ball').quantidade, 10);
    assert.equal(inventory.find((entry) => entry.itemId === ballReward.itemId).quantidade, 2);
    await db.desafioConcluido.create({ data: { saveId: save.id, desafioId: 'blue' } });
    assert.equal((await request(app).get('/api/batalhas/desafios').set(auth).expect(200)).body.data.regioes[0].escolhaSelvagem, true);
    const picked = (await request(app).post('/api/batalhas/iniciar').set(auth).send(custom).expect(201)).body.data;
    assert.equal(picked.oponente.especieId, 25);
    assert.equal(picked.oponente.nivel, 77);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    const mewtwo = { tipo: 'selvagem', regiao: 'kanto', selvagem: { regiao: 'kanto', especieId: 150, nivel: 77 } };
    await request(app).post('/api/batalhas/iniciar').set(auth).send(mewtwo).expect(403);
    await db.desafioConcluido.createMany({ data: ELITE.map((leader) => ({ saveId: save.id, desafioId: leader.id })) });
    assert.equal((await request(app).post('/api/batalhas/iniciar').set(auth).send(mewtwo).expect(201)).body.data.oponente.especieId, 150);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'johto' }).expect(403);
    await db.desafioConcluido.createMany({ data: GYMS.map((gym) => ({ saveId: save.id, desafioId: gym.id })) });
    const johtoStatus = (await request(app).get('/api/batalhas/desafios').set(auth).expect(200)).body.data;
    assert.equal(johtoStatus.regioes[1].desbloqueada, true);
    assert.equal(johtoStatus.regioes[1].escolhaSelvagem, false);
    const johtoWild = (await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'johto' }).expect(201)).body.data;
    assert.ok(johtoWild.oponente.especieId >= 152 && johtoWild.oponente.especieId <= 251);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    const johtoCustom = { tipo: 'selvagem', regiao: 'johto', selvagem: { regiao: 'johto', especieId: 152, nivel: 55 } };
    await request(app).post('/api/batalhas/iniciar').set(auth).send(johtoCustom).expect(403);
    await db.desafioConcluido.create({ data: { saveId: save.id, desafioId: 'johto-lance' } });
    const johtoPicked = (await request(app).post('/api/batalhas/iniciar').set(auth).send(johtoCustom).expect(201)).body.data;
    assert.equal(johtoPicked.oponente.especieId, 152);
    assert.equal(johtoPicked.oponente.nivel, 55);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'hoenn' }).expect(403);
    await db.desafioConcluido.createMany({ data: JOHTO_GYMS.map((gym) => ({ saveId: save.id, desafioId: gym.id })) });
    const hoennStatus = (await request(app).get('/api/batalhas/desafios').set(auth).expect(200)).body.data;
    assert.equal(hoennStatus.regioes[2].desbloqueada, true);
    assert.equal(hoennStatus.regioes[2].escolhaSelvagem, false);
    const hoennWild = (await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'hoenn' }).expect(201)).body.data;
    assert.ok(hoennWild.oponente.especieId >= 252 && hoennWild.oponente.especieId <= 386);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    const hoennCustom = { tipo: 'selvagem', regiao: 'hoenn', selvagem: { regiao: 'hoenn', especieId: 252, nivel: 65 } };
    await request(app).post('/api/batalhas/iniciar').set(auth).send(hoennCustom).expect(403);
    await db.desafioConcluido.create({ data: { saveId: save.id, desafioId: 'hoenn-steven' } });
    const hoennPicked = (await request(app).post('/api/batalhas/iniciar').set(auth).send(hoennCustom).expect(201)).body.data;
    assert.equal(hoennPicked.oponente.especieId, 252);
    assert.equal(hoennPicked.oponente.nivel, 65);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'sinnoh' }).expect(403);
    await db.desafioConcluido.createMany({ data: HOENN_GYMS.map((gym) => ({ saveId: save.id, desafioId: gym.id })) });
    const sinnohStatus = (await request(app).get('/api/batalhas/desafios').set(auth).expect(200)).body.data;
    assert.equal(sinnohStatus.regioes[3].desbloqueada, true);
    assert.equal(sinnohStatus.regioes[3].escolhaSelvagem, false);
    const sinnohWild = (await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'sinnoh' }).expect(201)).body.data;
    assert.ok(sinnohWild.oponente.especieId >= 387 && sinnohWild.oponente.especieId <= 493);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    const sinnohCustom = { tipo: 'selvagem', regiao: 'sinnoh', selvagem: { regiao: 'sinnoh', especieId: 387, nivel: 65 } };
    await request(app).post('/api/batalhas/iniciar').set(auth).send(sinnohCustom).expect(403);
    await db.desafioConcluido.create({ data: { saveId: save.id, desafioId: 'sinnoh-cynthia' } });
    const sinnohPicked = (await request(app).post('/api/batalhas/iniciar').set(auth).send(sinnohCustom).expect(201)).body.data;
    assert.equal(sinnohPicked.oponente.especieId, 387);
    assert.equal(sinnohPicked.oponente.nivel, 65);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'unova1' }).expect(403);
    await db.desafioConcluido.createMany({ data: SINNOH_GYMS.map((gym) => ({ saveId: save.id, desafioId: gym.id })) });
    const unova1Wild = (await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'unova1' }).expect(201)).body.data;
    assert.ok(unova1Wild.oponente.especieId >= 494 && unova1Wild.oponente.especieId <= 649);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'unova2' }).expect(403);
    await db.desafioConcluido.createMany({ data: UNOVA1_GYMS.map((gym) => ({ saveId: save.id, desafioId: gym.id })) });
    await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'unova2' }).expect(403);
    await db.desafioConcluido.create({ data: { saveId: save.id, desafioId: 'unova1-alder' } });
    const unova2Wild = (await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'unova2' }).expect(201)).body.data;
    assert.ok(unova2Wild.oponente.especieId >= 494 && unova2Wild.oponente.especieId <= 649);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'kalos' }).expect(403);
    await db.desafioConcluido.create({ data: { saveId: save.id, desafioId: 'unova2-iris' } });
    for (const [id, first, last, gyms] of [['kalos', 650, 721, KALOS_GYMS], ['alola', 722, 809, ALOLA_TRIALS], ['galar', 810, 905, GALAR_GYMS], ['paldea', 906, 1025, PALDEA_GYMS]]) {
      const wild = (await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: id }).expect(201)).body.data;
      assert.ok(wild.oponente.especieId >= first && wild.oponente.especieId <= last);
      await db.batalha.deleteMany({ where: { saveId: save.id } });
      await db.desafioConcluido.createMany({ data: gyms.map((gym) => ({ saveId: save.id, desafioId: gym.id })) });
    }
    await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'paldea', selvagem: { regiao: 'paldea', especieId: 1025, nivel: 100 } }).expect(403);
    await db.desafioConcluido.create({ data: { saveId: save.id, desafioId: 'paldea-geeta' } });
    await db.desafioConcluido.createMany({ data: PALDEA_ELITE.map((leader) => ({ saveId: save.id, desafioId: leader.id })) });
    const paldeaPicked = (await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'paldea', selvagem: { regiao: 'paldea', especieId: 1025, nivel: 100 } }).expect(201)).body.data;
    assert.equal(paldeaPicked.oponente.especieId, 1025);
    await db.batalha.deleteMany({ where: { saveId: save.id } });
    const allWild = (await request(app).post('/api/batalhas/iniciar').set(auth).send({ tipo: 'selvagem', regiao: 'todas' }).expect(201)).body.data;
    assert.ok(allWild.oponente.especieId >= 1 && allWild.oponente.especieId <= 1025);
  } finally {
    if (userId) {
      const save = await db.save.findUnique({ where: { usuarioId: userId } });
      if (save) {
        for (const model of ['batalha', 'desafioConcluido', 'especieRegistrada', 'pokemonCapturado', 'itemInventario']) await db[model].deleteMany({ where: { saveId: save.id } });
        await db.save.delete({ where: { id: save.id } });
      }
      await db.usuario.delete({ where: { id: userId } });
    }
    await db.$disconnect();
  }
});
