import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import '../../backend/src/config/env.js';
import { prisma } from '../../backend/src/lib/prisma.js';
import { getCatalogo } from '../../backend/src/services/catalogo.js';

test.afterAll(async () => { await prisma.$disconnect(); });

test('cadastro, novo jogo, inicial, menu, Pokedex, cancelamento e substituicao de save', async ({ page }, testInfo) => {
  const login = `ui_${randomUUID().replaceAll('-', '').slice(0, 20)}`;
  const senha = 'Ui-test-password-145!';
  const errors = [];
  const externalRequests = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('request', (request) => { if (!request.url().startsWith('http://127.0.0.1:5184') && !request.url().startsWith('data:')) externalRequests.push(request.url()); });
  try {
    await page.goto('/menu');
    await expect(page).toHaveURL(/\/login$/);
    await expect(page.getByRole('heading', { name: 'Bom ter você de volta.' })).toBeVisible();
    await expect(page.locator('.auth-form-wrap')).toHaveCSS('opacity', '1');
    await expect(page.locator('.starter-art img').last()).toHaveCSS('opacity', '1');
    await page.screenshot({ path: testInfo.outputPath('login.png'), fullPage: true });
    await page.getByRole('link', { name: 'Criar conta', exact: true }).click();
    await page.getByLabel('Nome do treinador', { exact: true }).fill('Treinador QA');
    await page.getByLabel('Usuário', { exact: true }).fill(login);
    await page.getByLabel('Senha', { exact: true }).fill(senha);
    await page.getByRole('button', { name: 'Criar minha conta' }).click();
    await expect(page).toHaveURL(/\/saves$/);
    await expect(page.getByRole('button', { name: 'Carregar save' })).toBeDisabled();
    await page.getByLabel('Nome do treinador', { exact: true }).fill('Leaf');
    await page.getByRole('button', { name: 'Começar novo jogo' }).click();
    await page.getByRole('button', { name: 'Começar jornada', exact: true }).click();
    await expect(page).toHaveURL(/\/inicial$/);
    await expect(page.getByRole('heading', { name: 'Uma escolha. Uma amizade para sempre.' })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Bulbasaur', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Johto · Geração II' }).click();
    await expect(page.getByRole('img', { name: 'Chikorita', exact: true })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Totodile', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Hoenn · Geração III' }).click();
    await expect(page.getByRole('img', { name: 'Treecko', exact: true })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Mudkip', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Sinnoh · Geração IV' }).click();
    await expect(page.getByRole('img', { name: 'Turtwig', exact: true })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Piplup', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Unova · Geração V' }).click();
    await expect(page.getByRole('img', { name: 'Snivy', exact: true })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Oshawott', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Kalos · Geração VI' }).click();
    await expect(page.getByRole('img', { name: 'Chespin', exact: true })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Froakie', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Alola · Geração VII' }).click();
    await expect(page.getByRole('img', { name: 'Rowlet', exact: true })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Popplio', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Galar · Geração VIII' }).click();
    await expect(page.getByRole('img', { name: 'Grookey', exact: true })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Sobble', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Paldea · Geração IX' }).click();
    await expect(page.getByRole('img', { name: 'Sprigatito', exact: true })).toBeVisible();
    await expect(page.getByRole('img', { name: 'Quaxly', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Kanto · Geração I' }).click();
    await expect(page.locator('.starter-card').last()).toHaveCSS('opacity', '1');
    await page.screenshot({ path: testInfo.outputPath('iniciais.png'), fullPage: true });
    await page.getByRole('button', { name: /#004/ }).click();
    await page.getByRole('button', { name: 'Escolher Charmander' }).click();
    await page.getByRole('button', { name: 'Confirmar meu parceiro' }).click();
    await expect(page).toHaveURL(/\/menu$/);
    await expect(page.getByRole('heading', { name: 'Olá, Leaf.' })).toBeVisible();
    await expect(page.getByText('1 NA COLEÇÃO')).toBeVisible();
    await page.getByRole('button', { name: 'Sair da conta' }).click();
    await page.getByLabel('Usuário', { exact: true }).fill(login);
    await page.getByLabel('Senha', { exact: true }).fill(senha);
    await page.getByRole('button', { name: 'Entrar na jornada' }).click();
    await expect(page).toHaveURL(/\/menu$/);
    await page.reload();
    await expect(page.getByText('1 NA COLEÇÃO')).toBeVisible();
    await expect(page.getByRole('checkbox', { name: 'Só itens que possuo' })).toBeChecked();
    await expect(page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Poção', exact: true }) }).first()).toContainText('×5');
    await page.screenshot({ path: testInfo.outputPath('menu.png'), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole('link', { name: 'Selvagens' }).first().click();
    await expect(page.getByRole('heading', { name: 'Explore a região.' })).toBeVisible();
    await expect(page.getByRole('button', { name: /Escolher Pokémon e nível/ })).toBeDisabled();
    await page.getByRole('button', { name: 'Todas as gerações liberadas' }).click();
    await expect(page.getByText('chance shiny conforme a geração encontrada')).toBeVisible();
    await page.getByRole('button', { name: 'Procurar Pokémon' }).click();
    await expect(page.getByRole('heading', { name: 'Escolha seu Pokémon após ver o adversário' })).toBeVisible();
    await expect(page.locator('.battle-foe > .variant-image')).toBeVisible();
    await page.reload();
    await expect(page.getByRole('heading', { name: 'Escolha seu Pokémon após ver o adversário' })).toBeVisible();
    await page.getByRole('button', { name: /Charmander.*#004.*Nv. 5/ }).click();
    await page.getByRole('button', { name: 'Escolher para batalhar' }).click();
    await expect(page.getByRole('heading', { name: /O que Charmander vai fazer/ })).toBeVisible();
    await expect(page.locator('.battle-moves button')).toHaveCount(1);
    await expect(page.locator('.battle-moves button').first()).toContainText('Scratch');
    await expect(page.locator('.effectiveness')).toContainText('×');
    await page.getByRole('button', { name: '3D' }).click();
    await expect(page.locator('.battle-arena .model-sprite')).toHaveCount(2);
    await expect(page.locator('.battle-player > .variant-image')).toHaveAttribute('alt', /de costas/);
    await expect(page.getByRole('group', { name: 'Item de cura' })).toBeVisible();
    await expect(page.getByRole('group', { name: 'Poké Bola' }).getByRole('button').first()).toHaveAttribute('aria-pressed', 'true');
    await page.screenshot({ path: testInfo.outputPath('batalha.png'), fullPage: true });
    await page.getByRole('button', { name: 'Fugir' }).click();
    await expect(page.getByRole('heading', { name: 'Você fugiu' })).toBeVisible();
    await page.getByRole('button', { name: 'Procurar novo Pokémon' }).click();
    await expect(page.getByRole('heading', { name: 'Escolha seu Pokémon após ver o adversário' })).toBeVisible();
    await page.getByRole('button', { name: /Charmander.*#004.*Nv. 5/ }).click();
    await page.getByRole('button', { name: 'Escolher para batalhar' }).click();
    await page.getByRole('button', { name: 'Fugir' }).click();
    await page.getByRole('button', { name: 'Escolher próxima batalha' }).click();
    await expect(page.getByRole('button', { name: 'Procurar Pokémon' })).toBeVisible();
    await page.getByRole('link', { name: 'Batalhas' }).first().click();
    await expect(page.getByRole('button', { name: /Fácil.*2–3 Pokémon/ })).toBeVisible();
    await page.getByRole('button', { name: 'Torneios' }).click();
    await expect(page.locator('.challenge-row')).toHaveCount(6);
    await expect(page.getByRole('button', { name: /Copa Prime/ })).toContainText('25.000 ₽');
    await expect(page.getByRole('button', { name: 'Pagar inscrição e começar' })).toBeDisabled();
    await page.getByRole('button', { name: 'Desafios' }).click();
    await expect(page.getByText('Lorelei').first()).toBeVisible();
    await expect(page.locator('.challenge-row').filter({ hasText: 'Lorelei' })).toBeDisabled();
    const currentUser = await prisma.usuario.findUnique({ where: { login }, include: { save: { include: { pokemons: true } } } });
    const charmander = currentUser.save.pokemons[0];
    await prisma.save.update({ where: { id: currentUser.save.id }, data: { moedas: 5000 } });
    await prisma.pokemonCapturado.update({ where: { id: charmander.id }, data: { nivel: 16, experiencia: getCatalogo().pokemon[3].experienciaPorNivel.find((entry) => entry.nivel === 16).experiencia } });
    await page.getByRole('link', { name: 'Início', exact: true }).click();
    await page.reload();
    await page.getByRole('button', { name: /Ver informações de Charmander/ }).click();
    await page.getByRole('button', { name: 'TMs' }).click();
    const flamethrower = page.locator('.tm-card').filter({ hasText: 'Flamethrower' });
    await expect(flamethrower).toBeVisible();
    await flamethrower.getByRole('button', { name: /Comprar/ }).click();
    await expect(flamethrower.getByRole('button', { name: 'Aprendido' })).toBeVisible();
    await page.getByRole('button', { name: 'Ataques' }).click();
    await page.getByRole('button', { name: 'Selecionar Flamethrower' }).click();
    await page.getByRole('button', { name: 'Remover Scratch' }).click();
    await page.getByRole('button', { name: 'Salvar ataques' }).click();
    await expect.poll(async () => (await prisma.pokemonCapturado.findUnique({ where: { id: charmander.id } })).golpes).toEqual([{ nome: 'flamethrower' }]);
    await page.getByRole('button', { name: 'Evolução' }).click();
    await expect(page.locator('.evolution-action').getByRole('img', { name: 'Charmeleon' })).toBeVisible();
    await expect(page.getByRole('button', { name: 'Evoluir', exact: true })).toBeEnabled();
    await page.getByRole('button', { name: 'Evoluir', exact: true }).click();
    await expect(page.getByRole('dialog').getByRole('heading', { name: 'Charmeleon', level: 2 })).toBeVisible();
    expect((await prisma.pokemonCapturado.findUnique({ where: { id: charmander.id } })).golpes).toEqual([{ nome: 'flamethrower' }]);
    await page.getByRole('button', { name: 'Fechar detalhes' }).click();
    await expect(page.getByRole('button', { name: /Ver informações de Charmeleon/ })).toBeVisible();
    await page.getByRole('link', { name: 'Perfil', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Insígnias dos ginásios' }).first()).toBeVisible();
    await expect(page.locator('.gym-badge')).toHaveCount(80);
    await prisma.desafioConcluido.create({ data: { saveId: currentUser.save.id, desafioId: 'blue' } });
    await page.getByRole('link', { name: 'Selvagens' }).first().click();
    await page.reload();
    await page.getByRole('button', { name: /Escolher Pokémon e nível/ }).click();
    await page.getByLabel('Buscar Pokémon selvagem').fill('#025');
    await page.locator('.wild-species-list button').first().click();
    await page.getByLabel('Nível desejado').fill('77');
    await page.getByRole('button', { name: 'Procurar Pokémon' }).click();
    await expect(page.getByText('Pikachu · Nv. 77')).toBeVisible();
    await page.getByRole('button', { name: 'Procurar outro Pokémon' }).click();
    await expect(page.getByText('Pikachu · Nv. 77')).toHaveCount(0);
    await page.getByRole('button', { name: 'Fugir' }).click();
    await expect(page.getByRole('heading', { name: 'Você fugiu' })).toBeVisible();
    await page.getByRole('button', { name: 'Procurar novo Pokémon' }).click();
    await page.getByRole('button', { name: /Charmeleon.*#005.*Nv. 16/ }).click();
    await page.getByRole('button', { name: 'Escolher para batalhar' }).click();
    await page.getByRole('button', { name: 'Fugir' }).click();
    await page.getByRole('button', { name: 'Escolher próxima batalha' }).click();
    await page.getByRole('link', { name: 'Batalhas' }).first().click();
    await page.getByRole('button', { name: 'Iniciar batalha' }).click();
    await expect(page.locator('.battle-topline')).toContainText('TREINADOR');
    await page.getByRole('button', { name: /Charmeleon.*#005.*Nv. 16/ }).click();
    await page.getByRole('button', { name: 'Escolher para batalhar' }).click();
    await expect(page.getByRole('heading', { name: /O que Charmeleon vai fazer/ })).toBeVisible();
    const trainerBattle = await prisma.batalha.findUnique({ where: { saveId: currentUser.save.id } });
    const winningState = structuredClone(trainerBattle.estado);
    winningState.fila = [];
    winningState.oponente.hp = 1;
    winningState.oponente.tipos = ['normal'];
    winningState.jogador.stats.speed = 999;
    winningState.jogador.ataques[0].poder = 10000;
    winningState.jogador.ataques[0].precisao = 100;
    await prisma.batalha.update({ where: { id: trainerBattle.id }, data: { estado: winningState } });
    await page.locator('.battle-moves button').first().click();
    await expect(page.getByRole('heading', { name: 'Vitória!' })).toBeVisible();
    await expect(page.locator('.battle-result')).toContainText('1.000 ₽');
    await expect(page.locator('.battle-result')).toContainText('Poké Bola');
    await page.getByRole('link', { name: 'Loja', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Loja Pokémon' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Catch Charm' })).toBeVisible();
    await page.getByLabel('Buscar item na loja').fill('ultra');
    await expect(page.getByRole('heading', { name: 'Ultra Bola' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Poção', exact: true })).toHaveCount(0);
    await page.getByLabel('Buscar item na loja').clear();
    await page.screenshot({ path: testInfo.outputPath('loja.png') });
    await page.getByRole('link', { name: 'Início', exact: true }).click();
    await expect(page.getByRole('checkbox', { name: 'Só itens que possuo' })).toBeChecked();
    await expect(page.getByRole('heading', { name: 'Captura' })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Cura' })).toBeVisible();
    await page.getByRole('group', { name: 'Filtrar itens por categoria' }).getByRole('button', { name: /Cura/ }).click();
    await expect(page.getByRole('heading', { name: 'Captura' })).toHaveCount(0);
    await page.getByRole('link', { name: /Pokédex/ }).first().click();
    await page.getByRole('textbox', { name: 'Buscar Pokémon' }).fill('#004');
    await expect(page.getByText('Capturado', { exact: true }).first()).toBeVisible();
    await page.getByRole('textbox', { name: 'Buscar Pokémon' }).fill('#151');
    await expect(page.getByRole('heading', { name: 'Mew', exact: true })).toBeVisible();
    await page.getByRole('textbox', { name: 'Buscar Pokémon' }).fill('#152');
    await expect(page.getByRole('heading', { name: 'Chikorita', exact: true })).toBeVisible();
    await page.getByRole('textbox', { name: 'Buscar Pokémon' }).fill('#252');
    await expect(page.getByRole('heading', { name: 'Treecko', exact: true })).toBeVisible();
    await page.getByLabel('Filtrar por geração').selectOption('3');
    await expect(page.getByRole('heading', { name: 'Treecko', exact: true })).toBeVisible();
    await page.getByRole('textbox', { name: 'Buscar Pokémon' }).fill('#387');
    await page.getByLabel('Filtrar por geração').selectOption('4');
    await expect(page.getByRole('heading', { name: 'Turtwig', exact: true })).toBeVisible();
    await page.getByRole('textbox', { name: 'Buscar Pokémon' }).fill('#495');
    await page.getByLabel('Filtrar por geração').selectOption('5');
    await expect(page.getByRole('heading', { name: 'Snivy', exact: true })).toBeVisible();
    for (const [generation, number, name] of [['6', '#650', 'Chespin'], ['7', '#722', 'Rowlet'], ['8', '#810', 'Grookey'], ['9', '#906', 'Sprigatito']]) {
      await page.getByRole('textbox', { name: 'Buscar Pokémon' }).fill(number);
      await page.getByLabel('Filtrar por geração').selectOption(generation);
      await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
    }
    await page.getByRole('textbox', { name: 'Buscar Pokémon' }).fill('nao-existe');
    await expect(page.getByText('Nenhum Pokémon encontrado. Tente outro nome ou tipo.')).toBeVisible();
    await page.getByRole('link', { name: 'Perfil', exact: true }).click();
    await page.getByRole('link', { name: 'Gerenciar saves' }).click();
    await page.getByRole('button', { name: 'Começar novo jogo' }).click();
    await page.getByRole('button', { name: 'Cancelar', exact: true }).click();
    await page.getByRole('button', { name: 'Carregar save' }).click();
    await expect(page).toHaveURL(/\/menu$/);
    await expect(page.getByText('1 NA COLEÇÃO')).toBeVisible();
    await page.getByRole('link', { name: 'Perfil', exact: true }).click();
    await page.getByRole('link', { name: 'Gerenciar saves' }).click();
    await page.getByLabel('Nome do treinador', { exact: true }).fill('Blue');
    await page.getByRole('button', { name: 'Começar novo jogo' }).click();
    await page.getByRole('button', { name: 'Substituir e começar' }).click();
    await expect(page).toHaveURL(/\/inicial$/);
    await page.goto('/menu');
    await expect(page).toHaveURL(/\/inicial$/);
    await page.getByRole('button', { name: 'Sair da conta' }).click();
    await expect(page).toHaveURL(/\/login$/);
    await page.getByLabel('Usuário', { exact: true }).fill(login);
    await page.getByLabel('Senha', { exact: true }).fill('Senha-incorreta');
    await page.getByRole('button', { name: 'Entrar na jornada' }).click();
    await expect(page.getByRole('alert')).toContainText('Login ou senha invalidos.');
    await page.getByLabel('Senha', { exact: true }).fill(senha);
    await page.getByRole('button', { name: 'Entrar na jornada' }).click();
    await expect(page).toHaveURL(/\/inicial$/);
    const user = await prisma.usuario.findUnique({ where: { login }, include: { save: { include: { pokemons: true } } } });
    expect(user.save.nomeTreinador).toBe('Blue');
    expect(user.save.pokemons).toHaveLength(0);
    expect(user.save.inicialEspecieId).toBeNull();
    expect(errors).toEqual([]);
    expect(externalRequests).toEqual([]);
  } finally {
    // Login unico gerado por este teste; nunca remove contas preexistentes.
    const existing = await prisma.usuario.findUnique({ where: { login }, include: { save: true } });
    if (existing?.save) {
      for (const model of ['batalha', 'desafioConcluido', 'especieRegistrada', 'pokemonCapturado', 'itemInventario']) await prisma[model].deleteMany({ where: { saveId: existing.save.id } });
      await prisma.save.delete({ where: { id: existing.save.id } });
    }
    if (existing) await prisma.usuario.delete({ where: { id: existing.id } });
  }
});
